### PR TITLE
Add option to send unchanged values over MQTT

### LINKED ISSUE #11: Add option to send unchanged values to help metrics db's
Could you add a config option to switch on and off the current behaviour of not re-sending a sensor value if it has not changed since the last message?  For example, currently if the ph value has not changed from the last reading we do not get ph/state resent mqtt message, but we do get ph/attr.
In certain scenarios it may help to get the update even if value has not changed (for example, plotting them in grafana)

### PR DESCRIPTION
**Pull request by LordMike**
Fixes #11

### CODE REVIEW

**Comment by LordMike** [comment]
Untested.

**Comment by ggggh** [comment]
Happy to test! are you publishing this branch under a docker tag?

**Comment by LordMike** [comment]
That's what i made #15 for. I realized I needed that :P

**Comment by LordMike** [comment]
So. There's dev images for the master branch. I'll make a test of this code, and then merge it to master so you can run the `dev` tag.

**Comment by LordMike** [comment]
This works fine. :)

**Comment by ggggh** [comment]
What is the right environment setting to activate this option?  Tried:  `ReportUnchangedValues: "true"` but unsuccessful.  (Had to use the string, as docker-compose won't take a boolean)

**Pull request merged**
